# PYTHON LIBS/VERSION
RECOMMENDED_PYTHON_VERSION = "3.13.2"
RECOMMENDED_PYTHON_LIBRARY_VERISONS_FILE = 'requirements.txt'

# SUPPORTED VERSIONS
SUPPORTED_OS_VERSIONS = ['windows', 'linux', 'darwin']

# CONFIG STUFF
CONFIG_FOLDER_NAME="hexa"
CONFIG_FILE_NAME=f"{CONFIG_FOLDER_NAME}/config.json"

# Logs
LOGS_FOLDER_NAME=f"{CONFIG_FOLDER_NAME}/logs"
LOGS_TEXT_FOLDER_NAME=f"{LOGS_FOLDER_NAME}/text"
LOGS_JSON_FOLDER_NAME=f"{LOGS_FOLDER_NAME}/json"

# Encryption
ENCRYPTION_FILE_LOCATION=f"{CONFIG_FOLDER_NAME}/key.txt"