# CONFIG STUFF
CONFIG_FOLDER_NAME="hexa"
CONFIG_FILE_NAME=f"{CONFIG_FOLDER_NAME}/config.json"

# Logs
LOGS_FOLDER_NAME="logs"
LOGS_TEXT_FOLDER_NAME=f"{LOGS_FOLDER_NAME}/text"
LOGS_JSON_FOLDER_NAME=f"{LOGS_FOLDER_NAME}/json"